async function checkProdApi() {
    try {
        const res = await fetch("https://www.clubdespetitsmagiciens.fr/api/test-bunny");
        const json = await res.json();
        console.log("Vercel API Response:", JSON.stringify(json, null, 2));

        if (json.kidsUrl) {
            console.log("\nTesting the live URL generated by Vercel:");
            const iframeRes = await fetch(json.kidsUrl);
            console.log("Iframe Status:", iframeRes.status);
            if (iframeRes.status !== 200) {
                 console.log("FAILED! The token generated by Vercel was rejected by Bunny. This means Vercel has the WRONG Token Key in its Environment Variables.");
            } else {
                 console.log("SUCCESS! The token generated by Vercel was accepted by Bunny.");
                 const html = await iframeRes.text();
                 
                 const cssIndex = html.indexOf('<style>');
                 if (cssIndex !== -1) {
                     console.log("Found CSS injection of size:", html.indexOf('</style>') - cssIndex);
                 } else {
                     console.log("No Custom CSS injection found in Iframe.");
                 }
            }
        }
    } catch (e) {
        console.error("Error:", e);
    }
}
checkProdApi();
